### ISSUE TITLE
libsass: "got unexpected keyword argument(s) 'image_path'"

### ISSUE THREAD

**Issue by moggers87** [miracle2k/webassets#438]
When trying to use the libsass filter, I get the following error:
```
TypeError: compile() got unexpected keyword argument(s) 'image_path'
```
It appears that libsass (as in the C++ library) hasn't supported `image_path` for nearly a year (<https://github.com/sass/libsass/pull/834>) and now the latest version of libsass-python has dropped support for arbitrary kwargs in `compile` (<https://github.com/dahlia/libsass-python/issues/109>) - thus causing an error as `image_path` isn't a valid kwarg.

Installing `libsass<0.10` works around this issue.

**Comment by moggers87** [comment]
I see this has already been fixed in master.

**Comment by teleyinex** [comment]
I'm still have this issue using Flask-Assets, that installs the latest assets version (0.11.1) but still has an old version. The only solution for me was to install using the following command:

pip install git+git://github.com/miracle2k/webassets.git

**Comment by oscarmlage** [comment]
I've same issue here with last version _0.12.3_. It's not happening with _.9.3_ for example.

**Comment by oscarmlage** [comment]
Using `webassets==0.11.1` here, this error is not shown when using it with `libsass==0.9.3` but it's shown again with last version of libsass (`0.12.1`), so it's probably on libsass' side. Take a look: https://github.com/sass/libsass/pull/834
